
language: node_js

env:
  - DATABASE_URL=postgres://coder:pg123@localhost:5432/towns
     
node_js:  
  - "8.9.4"
        
before_script:
  - psql -c 'create database  towns;' -U postgres
  - psql -U postgres -d towns -a -f database.sql

addons:
    apt:
    packages:
- postgresql-server-dev-9.2